FROM ubuntu:18.04
LABEL email="tmdghks0021@gmail.com"
LABEL name="seung"

RUN apt-get update 
RUN apt-get install -y apache2 apt-utils


EXPOSE 80
COPY ./2021_DEV_HTML /var/www/html/

ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

